// Code generated by "stringer -type=ControllerFormat"; DO NOT EDIT.

package particle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ControllerFormat_Unk0-0]
	_ = x[ControllerFormat_MinMax-1]
	_ = x[ControllerFormat_Cone-2]
	_ = x[ControllerFormat_Unk3-3]
	_ = x[ControllerFormat_Box-4]
	_ = x[ControllerFormat_Unk5-5]
	_ = x[ControllerFormat_Unk6-6]
	_ = x[ControllerFormat_Unk7-7]
	_ = x[ControllerFormat_Unk8-8]
	_ = x[ControllerFormat_Unk9-9]
	_ = x[ControllerFormat_Unk10-10]
	_ = x[ControllerFormat_Unk11-11]
	_ = x[ControllerFormat_Cylinder-12]
	_ = x[ControllerFormat_Unk13-13]
	_ = x[ControllerFormat_Unk14-14]
	_ = x[ControllerFormat_Unk15-15]
	_ = x[ControllerFormat_Unk16-16]
	_ = x[ControllerFormat_Unk17-17]
	_ = x[ControllerFormat_Unk18-18]
	_ = x[ControllerFormat_Unk19-19]
	_ = x[ControllerFormat_Unk20-20]
	_ = x[ControllerFormat_Unk21-21]
	_ = x[ControllerFormat_Unk22-22]
}

const _ControllerFormat_name = "ControllerFormat_Unk0ControllerFormat_MinMaxControllerFormat_ConeControllerFormat_Unk3ControllerFormat_BoxControllerFormat_Unk5ControllerFormat_Unk6ControllerFormat_Unk7ControllerFormat_Unk8ControllerFormat_Unk9ControllerFormat_Unk10ControllerFormat_Unk11ControllerFormat_CylinderControllerFormat_Unk13ControllerFormat_Unk14ControllerFormat_Unk15ControllerFormat_Unk16ControllerFormat_Unk17ControllerFormat_Unk18ControllerFormat_Unk19ControllerFormat_Unk20ControllerFormat_Unk21ControllerFormat_Unk22"

var _ControllerFormat_index = [...]uint16{0, 21, 44, 65, 86, 106, 127, 148, 169, 190, 211, 233, 255, 280, 302, 324, 346, 368, 390, 412, 434, 456, 478, 500}

func (i ControllerFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ControllerFormat_index)-1 {
		return "ControllerFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControllerFormat_name[_ControllerFormat_index[idx]:_ControllerFormat_index[idx+1]]
}
