// Code generated by "stringer -type=ControllerFormat"; DO NOT EDIT.

package particle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ControllerFormat_Unk0-0]
	_ = x[ControllerFormat_MinMax-1]
	_ = x[ControllerFormat_Cone-2]
	_ = x[ControllerFormat_Unk3-3]
	_ = x[ControllerFormat_Unk4-4]
	_ = x[ControllerFormat_Unk5-5]
	_ = x[ControllerFormat_Unk6-6]
	_ = x[ControllerFormat_Unk7-7]
	_ = x[ControllerFormat_Box-8]
	_ = x[ControllerFormat_Unk9-9]
	_ = x[ControllerFormat_Unk10-10]
	_ = x[ControllerFormat_Unk11-11]
	_ = x[ControllerFormat_Cylinder-12]
}

const _ControllerFormat_name = "ControllerFormat_Unk0ControllerFormat_MinMaxControllerFormat_ConeControllerFormat_Unk3ControllerFormat_Unk4ControllerFormat_Unk5ControllerFormat_Unk6ControllerFormat_Unk7ControllerFormat_BoxControllerFormat_Unk9ControllerFormat_Unk10ControllerFormat_Unk11ControllerFormat_Cylinder"

var _ControllerFormat_index = [...]uint16{0, 21, 44, 65, 86, 107, 128, 149, 170, 190, 211, 233, 255, 280}

func (i ControllerFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ControllerFormat_index)-1 {
		return "ControllerFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControllerFormat_name[_ControllerFormat_index[idx]:_ControllerFormat_index[idx+1]]
}
