// Code generated by "stringer -type=EmitterType"; DO NOT EDIT.

package particle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EmitterType_Unk0-0]
	_ = x[EmitterType_Rate-11]
	_ = x[EmitterType_Burst-12]
}

const (
	_EmitterType_name_0 = "EmitterType_Unk0"
	_EmitterType_name_1 = "EmitterType_RateEmitterType_Burst"
)

var (
	_EmitterType_index_1 = [...]uint8{0, 16, 33}
)

func (i EmitterType) String() string {
	switch {
	case i == 0:
		return _EmitterType_name_0
	case 11 <= i && i <= 12:
		i -= 11
		return _EmitterType_name_1[_EmitterType_index_1[i]:_EmitterType_index_1[i+1]]
	default:
		return "EmitterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
