// Code generated by "stringer -type=ComponentFormat"; DO NOT EDIT.

package particles

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComponentFormat_Unk0-0]
	_ = x[ComponentFormat_Unk1-1]
	_ = x[ComponentFormat_Unk2-2]
	_ = x[ComponentFormat_Unk3-3]
	_ = x[ComponentFormat_Unk4-4]
	_ = x[ComponentFormat_Unk5-5]
	_ = x[ComponentFormat_Unk6-6]
	_ = x[ComponentFormat_Unk7-7]
	_ = x[ComponentFormat_Unk8-8]
	_ = x[ComponentFormat_Unk9-9]
	_ = x[ComponentFormat_Unk10-10]
	_ = x[ComponentFormat_Unk11-11]
	_ = x[ComponentFormat_Unk12-12]
}

const _ComponentFormat_name = "ComponentFormat_Unk0ComponentFormat_Unk1ComponentFormat_Unk2ComponentFormat_Unk3ComponentFormat_Unk4ComponentFormat_Unk5ComponentFormat_Unk6ComponentFormat_Unk7ComponentFormat_Unk8ComponentFormat_Unk9ComponentFormat_Unk10ComponentFormat_Unk11ComponentFormat_Unk12"

var _ComponentFormat_index = [...]uint16{0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 221, 242, 263}

func (i ComponentFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ComponentFormat_index)-1 {
		return "ComponentFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentFormat_name[_ComponentFormat_index[idx]:_ComponentFormat_index[idx+1]]
}
