// Code generated by "stringer -type=VisualizerType"; DO NOT EDIT.

package particles

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VisualizerType_Billboard-0]
	_ = x[VisualizerType_Light-1]
	_ = x[VisualizerType_Mesh-2]
	_ = x[VisualizerType_Unk3-3]
	_ = x[VisualizerType_Trail-4]
}

const _VisualizerType_name = "VisualizerType_BillboardVisualizerType_LightVisualizerType_MeshVisualizerType_Unk3VisualizerType_Trail"

var _VisualizerType_index = [...]uint8{0, 24, 44, 63, 82, 102}

func (i VisualizerType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VisualizerType_index)-1 {
		return "VisualizerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VisualizerType_name[_VisualizerType_index[idx]:_VisualizerType_index[idx+1]]
}
